---
abstract: 'merge multiple Perl::Critic profiles into one'
author:
  - 'Sven Kirmess <sven.kirmess@kzone.ch>'
build_requires:
  Cwd: '0'
  Exporter: '5.57'
  File::Basename: '0'
  File::Path: '0'
  File::Spec: '0'
  Test::Fatal: '0'
  Test::MockModule: '0'
  Test::More: '0.88'
  lib: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla, CPAN::Meta::Converter'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Critic-MergeProfile
no_index:
  directory:
    - corpus
    - t
    - xt
requires:
  Carp: '0'
  Config::Tiny: '0'
  Scalar::Util: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/skirmess/Perl-Critic-MergeProfile/issues
  homepage: https://github.com/skirmess/Perl-Critic-MergeProfile
  repository: https://github.com/skirmess/Perl-Critic-MergeProfile.git
version: '0.003'
x_spdx_expression: BSD-2-Clause-FreeBSD
